import type { QuestionUploadRow } from '@/types'

/** Sample rows shown after simulated upload — validates client-side before commit to API */
export const QUESTION_UPLOAD_PREVIEW: QuestionUploadRow[] = [
  {
    row: 2,
    board: 'CBSE',
    grade: '8',
    subject: 'Mathematics',
    chapter: 'Algebra',
    topic: 'Linear Equations',
    difficulty: 'Medium',
    marks: 2,
    questionType: 'MCQ',
    text: 'Solve 3x − 5 = 10',
    optionA: 'x = 5',
    optionB: 'x = 3',
    optionC: 'x = 10',
    optionD: 'x = 15',
    correctAnswer: 'A',
    valid: true,
    errors: [],
  },
  {
    row: 3,
    board: 'CBSE',
    grade: '8',
    subject: 'Mathematics',
    chapter: 'Geometry',
    topic: 'Mensuration',
    difficulty: 'Hard',
    marks: 3,
    questionType: 'MCQ',
    text: 'Find area of trapezium with parallel sides 8cm and 12cm, height 5cm',
    optionA: '50 sq cm',
    optionB: '40 sq cm',
    optionC: '60 sq cm',
    optionD: '100 sq cm',
    correctAnswer: 'A',
    valid: true,
    errors: [],
  },
  {
    row: 4,
    board: 'CBSE',
    grade: '',
    subject: 'Mathematics',
    chapter: 'Algebra',
    topic: 'Linear Equations',
    difficulty: 'Easy',
    marks: 1,
    questionType: 'MCQ',
    text: 'What is 2 + 2?',
    valid: false,
    errors: ['Grade is required'],
  },
  {
    row: 5,
    board: 'CBSE',
    grade: '8',
    subject: 'Mathematics',
    chapter: 'Algebra',
    topic: 'Linear Equations',
    difficulty: 'Invalid',
    marks: 2,
    questionType: 'MCQ',
    text: 'Solve x + 1 = 5',
    valid: false,
    errors: ['Difficulty must be Easy / Medium / Hard'],
  },
  {
    row: 6,
    board: 'CBSE',
    grade: '8',
    subject: 'Science',
    chapter: 'Physics',
    topic: 'Motion & Force',
    difficulty: 'Medium',
    marks: 2,
    questionType: 'MCQ',
    text: 'Define acceleration',
    optionA: 'Rate of change of velocity',
    optionB: 'Rate of change of distance',
    optionC: 'Force per unit mass',
    optionD: 'Speed divided by time',
    correctAnswer: 'A',
    valid: true,
    errors: [],
  },
]
